name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install spchapi
      working-directory: ${{ github.workspace }}
      run: .\spchapi.exe
    - name: Install tv_enua
      working-directory: ${{ github.workspace }}
      run: .\tv_enua.exe
    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2
    - name: Build
      working-directory: ${{ github.workspace }}
      run: .\build.bat
